server:
  port: ${PORT:${SERVER_PORT:8080}}

spring:
  application:
    name: gateway
  zipkin:
    base-url: http://localhost:9411/
    enabled: true
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true

      routes:
        - id: mscatalogService #identificador de la ruta
          uri: lb://catalog-service #URL donde se hará el redirect segun el predicado definido
          predicates: #Reglas de analisis de request
            - Path=/catalog/** #path de url de request a considerar


info:
  app:
    name: ${spring.application.name}

eureka:
  client:
    registerWithEureka: false
    fetchRegistry: true
    serviceURL:
      defaultZone: http://localhost:8761/eureka
  management:
    endpoint:
      gateway:
        enabled: true
    endpoints:
      web:
        exposure:
          include: gateway
