spring:
  mongodb:
    embedded:
      version: 4.0.2
  data:
    mongodb:
      database: test1
      port: 27018
  zipkin:
    base-url: http://localhost:9411/
    enabled: true

server:
  port: ${PORT:${SERVER_PORT:0}}
  idRandom: ${random.value}


eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${vcap.application.instance_id:${spring.application.instance_id:${random.value}}}

queue:
  serie:
    name: SerieQueue
